index:
    path: /
    controller: App\Controller\PagesController::index

blog:
    path: /blog
    controller: App\Controller\BlogController::index


add_post:
    path: /add-post
    controller: App\Controller\PostController::add

